import userlogo from "../../../../../Assets/img/userlogo.png"


const Traders=[
    {
        id:"1",
        img: userlogo,
        Name: 'other users name',
        type: "CRYSTAL TRADERS",
        earned: "$223,43.24",
        totalPNL: "223%",
        OpnPositions: "123",
        Followers: "321",
        Follow:false,
        Copying:false
    },
    {
        id:"2",
        img: userlogo,
        Name: 'other users name',
        type: "CRYSTAL TRADERS",
        earned: "$223,43.24",
        totalPNL: "223%",
        OpnPositions: "123",
        Followers: "321",
        Follow:true,
        Copying:false
    },
    {
        id:"3",
        img: userlogo,
        Name: 'other users name',
        type: "CRYSTAL TRADERS",
        earned: "$223,43.24",
        totalPNL: "223%",
        OpnPositions: "123",
        Followers: "321",
        Follow:true,
        Copying:true
    },
    {
        id:"4",
        img: userlogo,
        Name: 'other users name',
        type: "CRYSTAL TRADERS",
        earned: "$223,43.24",
        totalPNL: "223%",
        OpnPositions: "123",
        Followers: "321",
        Follow:true,
        Copying:false
    },
    {
        id:"5",
        img: userlogo,
        Name: 'other users name',
        type: "CRYSTAL TRADERS",
        earned: "$223,43.24",
        totalPNL: "223%",
        OpnPositions: "123",
        Followers: "321",
        Follow:true,
        Copying:true
    },
    {
        id:"6",
        img: userlogo,
        Name: 'other users name',
        type: "CRYSTAL TRADERS",
        earned: "$223,43.24",
        totalPNL: "223%",
        OpnPositions: "123",
        Followers: "321",
        Follow:true,
        Copying:false
    },
    {
        id:"6",
        img: userlogo,
        Name: 'other users name',
        type: "CRYSTAL TRADERS",
        earned: "$223,43.24",
        totalPNL: "223%",
        OpnPositions: "123",
        Followers: "321",
        Follow:false,
        Copying:false
    },
    {
        id:"6",
        img: userlogo,
        Name: 'other users name',
        type: "CRYSTAL TRADERS",
        earned: "$223,43.24",
        totalPNL: "223%",
        OpnPositions: "123",
        Followers: "321",
        Follow:true,
        Copying:true
    },
    {
        id:"6",
        img: userlogo,
        Name: 'other users name',
        type: "CRYSTAL TRADERS",
        earned: "$223,43.24",
        totalPNL: "223%",
        OpnPositions: "123",
        Followers: "321",
        Follow:false,
        Copying:true
    },
    {
        id:"6",
        img: userlogo,
        Name: 'other users name',
        type: "CRYSTAL TRADERS",
        earned: "$223,43.24",
        totalPNL: "223%",
        OpnPositions: "123",
        Followers: "321",
        Follow:true,
        Copying:true
    },
    {
        id:"6",
        img: userlogo,
        Name: 'other users name',
        type: "CRYSTAL TRADERS",
        earned: "$223,43.24",
        totalPNL: "223%",
        OpnPositions: "123",
        Followers: "321",
        Follow:true,
        Copying:true
    },
    {
        id:"6",
        img: userlogo,
        Name: 'other users name',
        type: "CRYSTAL TRADERS",
        earned: "$223,43.24",
        totalPNL: "223%",
        OpnPositions: "123",
        Followers: "321",
        Follow:false,
        Copying:true
    },
    {
        id:"6",
        img: userlogo,
        Name: 'other users name',
        type: "CRYSTAL TRADERS",
        earned: "$223,43.24",
        totalPNL: "223%",
        OpnPositions: "123",
        Followers: "321",
        Follow:true,
        Copying:false
    },
    {
        id:"6",
        img: userlogo,
        Name: 'other users name',
        type: "CRYSTAL TRADERS",
        earned: "$223,43.24",
        totalPNL: "223%",
        OpnPositions: "123",
        Followers: "321",
        Follow:false,
        Copying:false
    },
    {
        id:"6",
        img: userlogo,
        Name: 'other users name',
        type: "CRYSTAL TRADERS",
        earned: "$223,43.24",
        totalPNL: "223%",
        OpnPositions: "123",
        Followers: "321",
        Follow:true,
        Copying:true
    },
    {
        id:"6",
        img: userlogo,
        Name: 'other users name',
        type: "CRYSTAL TRADERS",
        earned: "$223,43.24",
        totalPNL: "223%",
        OpnPositions: "123",
        Followers: "321",
        Follow:true,
        Copying:false
    },
    {
        id:"6",
        img: userlogo,
        Name: 'other users name',
        type: "CRYSTAL TRADERS",
        earned: "$223,43.24",
        totalPNL: "223%",
        OpnPositions: "123",
        Followers: "321",
        Follow:false,
        Copying:true
    },
    {
        id:"6",
        img: userlogo,
        Name: 'other users name',
        type: "CRYSTAL TRADERS",
        earned: "$223,43.24",
        totalPNL: "223%",
        OpnPositions: "123",
        Followers: "321",
        Follow:true,
        Copying:true
    },
    {
        id:"6",
        img: userlogo,
        Name: 'other users name',
        type: "CRYSTAL TRADERS",
        earned: "$223,43.24",
        totalPNL: "223%",
        OpnPositions: "123",
        Followers: "321",
        Follow:false,
        Copying:false
    },
]

export default Traders