
import userlogo from '../../../../../Assets/img/userlogo.png'

const UserData = {
    Profile: {
        id: '1',
        Name: 'username',
        following: 23,
        followers: 12,
        positions: 62,
        totalTraders: 892,
        totalPNLper: 92.19,
        totalPNL: 942,
        dailyPNL: 2237,
        activeTrad: 23,
        tradCop: 892,
        fundedAccount: 62,
        img: userlogo
    },
    Traders: [
        {
            id: "1",
            img: userlogo,
            Name: 'other users name',
            type: "CRYSTAL TRADERS",
            earned: "$223,43.24",
            totalPNL: "223%",
            OpnPositions: "123",
            Followers: "321",
            Follow: false,
            Copying: false
        },
        {
            id: "2",
            img: userlogo,
            Name: 'other users name',
            type: "CRYSTAL TRADERS",
            earned: "$223,43.24",
            totalPNL: "223%",
            OpnPositions: "123",
            Followers: "321",
            Follow: true,
            Copying: false
        },
        {
            id: "3",
            img: userlogo,
            Name: 'other users name',
            type: "CRYSTAL TRADERS",
            earned: "$223,43.24",
            totalPNL: "223%",
            OpnPositions: "123",
            Followers: "321",
            Follow: true,
            Copying: true
        },
        {
            id: "4",
            img: userlogo,
            Name: 'other users name',
            type: "CRYSTAL TRADERS",
            earned: "$223,43.24",
            totalPNL: "223%",
            OpnPositions: "123",
            Followers: "321",
            Follow: true,
            Copying: false
        },
        {
            id: "5",
            img: userlogo,
            Name: 'other users name',
            type: "CRYSTAL TRADERS",
            earned: "$223,43.24",
            totalPNL: "223%",
            OpnPositions: "123",
            Followers: "321",
            Follow: true,
            Copying: true
        },
        {
            id: "6",
            img: userlogo,
            Name: 'other users name',
            type: "CRYSTAL TRADERS",
            earned: "$223,43.24",
            totalPNL: "223%",
            OpnPositions: "123",
            Followers: "321",
            Follow: true,
            Copying: false
        },
        {
            id: "6",
            img: userlogo,
            Name: 'other users name',
            type: "CRYSTAL TRADERS",
            earned: "$223,43.24",
            totalPNL: "223%",
            OpnPositions: "123",
            Followers: "321",
            Follow: false,
            Copying: false
        },
        {
            id: "6",
            img: userlogo,
            Name: 'other users name',
            type: "CRYSTAL TRADERS",
            earned: "$223,43.24",
            totalPNL: "223%",
            OpnPositions: "123",
            Followers: "321",
            Follow: true,
            Copying: true
        },
        {
            id: "6",
            img: userlogo,
            Name: 'other users name',
            type: "CRYSTAL TRADERS",
            earned: "$223,43.24",
            totalPNL: "223%",
            OpnPositions: "123",
            Followers: "321",
            Follow: false,
            Copying: true
        },
        {
            id: "6",
            img: userlogo,
            Name: 'other users name',
            type: "CRYSTAL TRADERS",
            earned: "$223,43.24",
            totalPNL: "223%",
            OpnPositions: "123",
            Followers: "321",
            Follow: true,
            Copying: true
        },
        {
            id: "6",
            img: userlogo,
            Name: 'other users name',
            type: "CRYSTAL TRADERS",
            earned: "$223,43.24",
            totalPNL: "223%",
            OpnPositions: "123",
            Followers: "321",
            Follow: true,
            Copying: true
        },
        {
            id: "6",
            img: userlogo,
            Name: 'other users name',
            type: "CRYSTAL TRADERS",
            earned: "$223,43.24",
            totalPNL: "223%",
            OpnPositions: "123",
            Followers: "321",
            Follow: false,
            Copying: true
        },
        {
            id: "6",
            img: userlogo,
            Name: 'other users name',
            type: "CRYSTAL TRADERS",
            earned: "$223,43.24",
            totalPNL: "223%",
            OpnPositions: "123",
            Followers: "321",
            Follow: true,
            Copying: false
        },
        {
            id: "6",
            img: userlogo,
            Name: 'other users name',
            type: "CRYSTAL TRADERS",
            earned: "$223,43.24",
            totalPNL: "223%",
            OpnPositions: "123",
            Followers: "321",
            Follow: false,
            Copying: false
        },
        {
            id: "6",
            img: userlogo,
            Name: 'other users name',
            type: "CRYSTAL TRADERS",
            earned: "$223,43.24",
            totalPNL: "223%",
            OpnPositions: "123",
            Followers: "321",
            Follow: true,
            Copying: true
        },
        {
            id: "6",
            img: userlogo,
            Name: 'other users name',
            type: "CRYSTAL TRADERS",
            earned: "$223,43.24",
            totalPNL: "223%",
            OpnPositions: "123",
            Followers: "321",
            Follow: true,
            Copying: false
        },
        {
            id: "6",
            img: userlogo,
            Name: 'other users name',
            type: "CRYSTAL TRADERS",
            earned: "$223,43.24",
            totalPNL: "223%",
            OpnPositions: "123",
            Followers: "321",
            Follow: false,
            Copying: true
        },
        {
            id: "6",
            img: userlogo,
            Name: 'other users name',
            type: "CRYSTAL TRADERS",
            earned: "$223,43.24",
            totalPNL: "223%",
            OpnPositions: "123",
            Followers: "321",
            Follow: true,
            Copying: true
        },
        {
            id: "6",
            img: userlogo,
            Name: 'other users name',
            type: "CRYSTAL TRADERS",
            earned: "$223,43.24",
            totalPNL: "223%",
            OpnPositions: "123",
            Followers: "321",
            Follow: false,
            Copying: false
        },
    ]
}

export default UserData;